import Head from "next/head";
import { Inter } from "@next/font/google";
import { Hero } from "src/sections";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Mahdi Murshed</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://github.com/MahdiMurshed.png" />
      </Head>
      <main className={`${inter.className} bg-p-bg text-p-txt`}>
        <Hero />
      </main>
    </>
  );
}
